#include "pomp_lib.h"

struct ompregdescr omp_rd_25 = {
  "parallelfor", "", 0, "fft_parallel.c", 108, 108, 112, 112
};

#define POMP_DLIST_00025 shared(omp_rd_25)

struct ompregdescr omp_rd_26 = {
  "parallelfor", "", 0, "fft_parallel.c", 123, 123, 128, 128
};

#define POMP_DLIST_00026 shared(omp_rd_26)

struct ompregdescr omp_rd_27 = {
  "parallelfor", "", 0, "fft_parallel.c", 130, 130, 135, 135
};

#define POMP_DLIST_00027 shared(omp_rd_27)

struct ompregdescr omp_rd_28 = {
  "parallelfor", "", 0, "fft_parallel.c", 138, 138, 142, 142
};

#define POMP_DLIST_00028 shared(omp_rd_28)

struct ompregdescr omp_rd_29 = {
  "parallelfor", "", 0, "fft_parallel.c", 148, 148, 152, 152
};

#define POMP_DLIST_00029 shared(omp_rd_29)

struct ompregdescr omp_rd_30 = {
  "parallelfor", "", 0, "fft_parallel.c", 158, 158, 163, 163
};

#define POMP_DLIST_00030 shared(omp_rd_30)

struct ompregdescr omp_rd_31 = {
  "parallelfor", "", 0, "fft_parallel.c", 166, 166, 170, 170
};

#define POMP_DLIST_00031 shared(omp_rd_31)

struct ompregdescr omp_rd_32 = {
  "parallel", "", 0, "fft_parallel.c", 175, 175, 179, 179
};

#define POMP_DLIST_00032 shared(omp_rd_32)

